framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            order_rpc:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order_exchange
                        type: topic
                    queues:
                        order_create_rpc: ~

            order_response:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order_response_exchange
                        type: fanout
                    queues:
                        order_response_queue: ~
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # повідомлення йдуть через RabbitMQ до order service
            App\Message\CreateOrder: order_rpc
            App\Message\OrderResponse: order_response

